routes/web.php
<?php

/* Admin Routes */

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.'], function () {

    /*
     *  admin login and logout routes
     */

    Route::group(['prefix' => 'auth', 'as' => 'auth.'], function () {


        Route::get('/login', ['uses' => 'AuthController@index', 'as' => 'get.login']);

        Route::post('/login', ['uses' => 'AuthController@login', 'as' => 'post.login']);

        Route::get('/logout', ['uses' => 'AuthController@logout', 'as' => 'logout']);


    });


    /*Must Login Routes*/

    Route::group(['middleware' => 'admin'], function () {

        /*
         * Change Lang
         */
        Route::group(['as' => 'lang.'], function () {
            Route::get('/lang', ['uses' => 'IndexController@changeLang', 'as' => 'change']);
        });

        /*
        * Dashboard
        */
        Route::group(['as' => 'index.'], function () {
            Route::get('/', ['uses' => 'IndexController@index', 'as' => 'index']);
        });

        /*
                 * Profile
                 */
        Route::group(['prefix' => 'profile', 'as' => 'profile.'], function () {
            Route::get('/', ['uses' => 'ProfileController@index', 'as' => 'index']);
            Route::post('/update', ['uses' => 'ProfileController@update', 'as' => 'update']);
            Route::post('/update-password', ['uses' => 'ProfileController@updatePassword', 'as' => 'update.password']);
        });


        /*
         * Admins
         */
        Route::group(['prefix' => 'admins', 'as' => 'admins.'], function () {

            Route::get('/', ['uses' => 'AdminsController@index', 'as' => 'index']);
            Route::post('/add-admin', ['uses' => 'AdminsController@add', 'as' => 'add']);
            Route::post('/edit-admin', ['uses' => 'AdminsController@edit', 'as' => 'edit']);
            Route::post('/delete-admin', ['uses' => 'AdminsController@delete', 'as' => 'delete']);

        });

        /*
         * Roles
         */
        Route::group(['prefix' => 'roles', 'as' => 'roles.'], function () {

            Route::get('/', ['uses' => 'RolesController@index', 'as' => 'index']);
            Route::post('/add-role', ['uses' => 'RolesController@add', 'as' => 'add']);
            Route::post('/edit-role', ['uses' => 'RolesController@edit', 'as' => 'edit']);
            Route::post('/delete-role', ['uses' => 'RolesController@delete', 'as' => 'delete']);

        });


        /*
        * Settings
        */
        Route::group(['prefix' => 'settings', 'as' => 'settings.'], function () {

            Route::get('/', ['uses' => 'SettingsController@index', 'as' => 'index']);

            // Site details
            Route::post('/edit-details', ['uses' => 'SettingsController@editSiteDetails', 'as' => 'edit.details']);

            // Social
            Route::post('/edit-social', ['uses' => 'SettingsController@editSocial', 'as' => 'edit.social']);

            // About us
            Route::post('/edit-about', ['uses' => 'SettingsController@editAbout', 'as' => 'edit.about']);

            // Team
            Route::post('/add-team', ['uses' => 'SettingsController@addTeam', 'as' => 'add.team']);
            Route::post('/edit-team', ['uses' => 'SettingsController@editTeam', 'as' => 'edit.team']);
            Route::post('/delete-team', ['uses' => 'SettingsController@deleteTeam', 'as' => 'delete.team']);

            // gallery department
            Route::post('/add-gallery-department', ['uses' => 'SettingsController@addGalleryDepartment', 'as' => 'add.gallery.department']);
            Route::post('/edit-gallery-department', ['uses' => 'SettingsController@editGalleryDepartment', 'as' => 'edit.gallery.department']);
            Route::post('/delete-gallery-department', ['uses' => 'SettingsController@deleteGalleryDepartment', 'as' => 'delete.gallery.department']);


            // Gallery
            Route::post('/add-gallery', ['uses' => 'SettingsController@addGallrey', 'as' => 'add.gallery']);
            Route::post('/edit-gallery', ['uses' => 'SettingsController@editGallrey', 'as' => 'edit.gallery']);
            Route::post('/delete-gallery', ['uses' => 'SettingsController@deleteGallrey', 'as' => 'delete.gallery']);

            Route::post('/add-article', ['uses' => 'SettingsController@addArticle', 'as' => 'add.article']);
            Route::post('/edit-article', ['uses' => 'SettingsController@editArticle', 'as' => 'edit.article']);
            Route::post('/delete-article', ['uses' => 'SettingsController@deleteArticle', 'as' => 'delete.article']);

            // Services
            Route::post('/add-service', ['uses' => 'SettingsController@addService', 'as' => 'add.service']);
            Route::post('/edit-service', ['uses' => 'SettingsController@editService', 'as' => 'edit.service']);
            Route::post('/delete-service', ['uses' => 'SettingsController@deleteService', 'as' => 'delete.service']);

            // Web Colors
            Route::post('/edit-web-color', ['uses' => 'SettingsController@editWebColor', 'as' => 'edit.web.color']);

            // Mobile Colors
            Route::post('/edit-mobile-color', ['uses' => 'SettingsController@editMobileColor', 'as' => 'edit.mobile.color']);

            // Web Slider
            Route::post('/add-web-slider', ['uses' => 'SettingsController@addWebSlider', 'as' => 'add.web.slider']);
            Route::post('/edit-web-slider', ['uses' => 'SettingsController@editWebSlider', 'as' => 'edit.web.slider']);
            Route::post('/delete-web-slider', ['uses' => 'SettingsController@deleteWebSlider', 'as' => 'delete.web.slider']);
            Route::post('/web-slider-status', ['uses' => 'SettingsController@webSliderStatus', 'as' => 'web.slider.status']);

            // Mobile Slider
            Route::post('/add-mobile-slider', ['uses' => 'SettingsController@addMobileSlider', 'as' => 'add.mobile.slider']);
            Route::post('/edit-mobile-slider', ['uses' => 'SettingsController@editMobileSlider', 'as' => 'edit.mobile.slider']);
            Route::post('/delete-mobile-slider', ['uses' => 'SettingsController@deleteMobileSlider', 'as' => 'delete.mobile.slider']);
            Route::post('/mobile-slider-status', ['uses' => 'SettingsController@mobileSliderStatus', 'as' => 'mobile.slider.status']);

            Route::post('/add-testmonials', ['uses' => 'SettingsController@addTestmonials', 'as' => 'add.testmonials']);
            Route::post('/edit-testmonials', ['uses' => 'SettingsController@editTestmonials', 'as' => 'edit.testmonials']);
            Route::post('/delete-testmonials', ['uses' => 'SettingsController@deleteTestmonials', 'as' => 'delete.testmonials']);

            Route::post('/add-customer-logo', ['uses' => 'SettingsController@addCustomerLogo', 'as' => 'add.customer.logo']);
            Route::post('/edit-customer-logo', ['uses' => 'SettingsController@editCustomerLogo', 'as' => 'edit.customer.logo']);
            Route::post('/delete-customer-logo', ['uses' => 'SettingsController@deleteCustomerLogo', 'as' => 'delete.customer.logo']);

            Route::post('/add-condition', ['uses' => 'SettingsController@addCondition', 'as' => 'add.condition']);
            Route::post('/edit-condition', ['uses' => 'SettingsController@editCondition', 'as' => 'edit.condition']);
            Route::post('/delete-condition', ['uses' => 'SettingsController@deleteCondition', 'as' => 'delete.condition']);

            Route::post('/add-question', ['uses' => 'SettingsController@addQuestion', 'as' => 'add.question']);
            Route::post('/edit-question', ['uses' => 'SettingsController@editQuestion', 'as' => 'edit.question']);
            Route::post('/delete-question', ['uses' => 'SettingsController@deleteQuestion', 'as' => 'delete.question']);

            Route::post('/add-info', ['uses' => 'SettingsController@addInfo', 'as' => 'add.info']);
            Route::post('/edit-info', ['uses' => 'SettingsController@editInfo', 'as' => 'edit.info']);
            Route::post('/delete-info', ['uses' => 'SettingsController@deleteInfo', 'as' => 'delete.info']);

            Route::post('/add-shi-condition', ['uses' => 'SettingsController@addShCondition', 'as' => 'add.sh.condition']);
            Route::post('/edit-shi-condition', ['uses' => 'SettingsController@editShCondition', 'as' => 'edit.sh.condition']);
            Route::post('/delete-shi-condition', ['uses' => 'SettingsController@deleteShCondition', 'as' => 'delete.sh.condition']);

            // Time

            Route::post('/edit-time', ['uses' => 'SettingsController@editTime', 'as' => 'edit.time']);
            Route::post('/edit-status', ['uses' => 'SettingsController@editStatus', 'as' => 'edit.status']);

            Route::group(['prefix' => 'countries'], function () {

                Route::post('/add-country', ['uses' => 'SettingsController@AddCountry', 'as' => 'add.country']);
                Route::post('/edit-country', ['uses' => 'SettingsController@EditCountry', 'as' => 'edit.country']);
                Route::post('/delete-country', ['uses' => 'SettingsController@DeleteCountry', 'as' => 'delete.country']);

            });

            Route::group(['prefix' => 'provinces'], function () {

                Route::get('/{id}', ['uses' => 'SettingsController@Provinces', 'as' => 'provinces']);
                Route::post('/add-province', ['uses' => 'SettingsController@AddProvince', 'as' => 'add.province']);
                Route::post('/edit-province', ['uses' => 'SettingsController@EditProvince', 'as' => 'edit.province']);
                Route::post('/delete-province', ['uses' => 'SettingsController@DeleteProvince', 'as' => 'delete.province']);

            });

            Route::group(['prefix' => 'cities'], function () {

                Route::get('/{id}', ['uses' => 'SettingsController@Cities', 'as' => 'cities']);
                Route::post('/add-city', ['uses' => 'SettingsController@AddCity', 'as' => 'add.city']);

resources/views/admin/layouts/Master-Layout.blade.php
<!DOCTYPE html>

<html lang="en" class="smart-style-1">

<head>
    <title>@yield('title')</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,300,400,500,700">
    <link rel="shortcut icon" href="{{site_details()->icon ? site_details()->icon : asset('default-logo.jpg')}}  "
          type="image/x-icon">
    <link rel="icon" href="{{site_details()->icon ? site_details()->icon : asset('default-logo.jpg')}}  "
          type="image/x-icon">

    <link href="{{ asset('css/admin.css')}}" media="all" rel="stylesheet" type="text/css"/>
    <link href="{{ asset('site/css/font-awesome.min.css')}}" media="all" rel="stylesheet" type="text/css"/>

    @if (app()->getLocale() == 'ar')
        <link href="{{ asset('backEnd/css/smartadmin-rtl.min.css')}}" media="all" rel="stylesheet" type="text/css"/>
    @endif
</head>

<body class="smart-style-1 " @if (app()->getLocale() == 'ar') dir="rtl" @endif>

<!-- BEGIN .sa-wrapper -->
<div class="sa-wrapper">
    <!-- BEGIN .sa-shortcuts -->

    <div class="sa-shortcuts-section">
        <ul>
            <li><a class="bg-pink-dark selected" href="{{route('admin.profile.index')}}"><span
                            class="fa fa-user fa-4x"></span><span
                            class="box-caption">{{trans('admin.profile')}}</span><em class="counter"></em></a></li>
        </ul>
    </div>
    <!-- END .sa-shortcuts -->

    <header class="sa-page-header">
        <div class="sa-header-container h-100">
            <div class="d-table d-table-fixed h-100 w-100">
                <div class="sa-logo-space d-table-cell h-100">
                    <div class="flex-row d-flex align-items-center h-100">
                        <a class="sa-logo-link" href="" title="Smart Admin 2.0"><img alt="Smart Admin 2.0"
                                                                                     src="{{site_details()->logo ? asset('uploads/site_details/' . site_details()->logo) :  asset('default-logo.jpg')}}"
                                                                                     class="sa-logo"></a>
                        <div class="dropdown ml-auto">
                            <button class="btn btn-default sa-btn-icon sa-activity-dropdown-toggle" type="button"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span
                                        class="fa fa-user"></span><span class="badge bg-red">0</span></button>
                            <div class="dropdown-menu ml-auto ajax-dropdown" aria-labelledby="dropdownMenuButton">
                                <form class="btn-group btn-group-justified" role="group" aria-label="Basic example">
                                    <button type="button" class="btn btn-default"> (0)
                                    </button>
                                </form>
                                <ul>
                                    <li>message 1</li>
                                    <li>message 2</li>
                                </ul>

                            </div>
                        </div>
                    </div>
                </div>
                <div class="d-table-cell h-100 w-100 align-middle">
                    <div class="sa-header-menu">
                        <div class="d-flex align-items-center w-100">
                            <div class="ml-auto sa-header-right-area">
                                <div class="form-inline">
										<span class="dropdown sa-country-dropdown">
											<a href="javascript:void(0);" data-toggle="dropdown" aria-haspopup="true"
                                               aria-expanded="false"><em class="flag flag-us"></em> <span> @if (app()->getLocale() == 'ar')
                                                        {{trans('admin.lang.ar')}}
                                                    @else
                                                        {{trans('admin.lang.en')}}
                                                    @endif
                                                     <span class="fa fa-angle-down"></span></span></a>
                                             <span class="dropdown-menu dropdown-menu-right ml-auto"
                                                   aria-labelledby="dropdownMenuButton">
                                                 <a class="dropdown-item @if (app()->getLocale() == 'en') active @endif "
                                                    href="{{route('admin.lang.change',['lang'=>'en'])}}"><span
                                                             class="flag flag-us"></span>
                                                     English</a>
												<a class="dropdown-item @if (app()->getLocale() == 'ar') active @endif "
                                                   href="{{route('admin.lang.change',['lang'=>'ar'])}}"><span
                                                            class="flag flag-fr"></span>
													العربيه</a>

											</span>
										</span>
                                    {{--                                    {{dd(app()->getLocale())}}--}}
                                    <button
                                            class="btn btn-light sa-btn-icon sa-toggle-full-screen d-none d-lg-block"
                                            type="button" onclick="toggleFullScreen()"><span
                                                class="fa fa-arrows-alt"></span></button>

                                    <a class="btn btn-default  sa-btn-icon"
                                       type="button" href="{{route('admin.auth.logout')}}"><span
                                                class="fa fa-sign-out"></span></a>
                                    <button class="btn btn-default sa-btn-icon sa-sidebar-hidden-toggle"
                                            onclick="SAtoggleClass(this, 'body', 'sa-hidden-menu')" type="button"><span
                                                class="fa fa-reorder"></span></button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- END .sa-page-header -->
    <div class="sa-page-body">
        <!-- BEGIN .sa-aside-left -->
        <div class="sa-aside-left">
            <a href="javascript:void(0)" onclick="SAtoggleClass(this, 'body', 'sa-shortcuts-expanded')"
               class="sa-sidebar-shortcut-toggle">
                <img src="{{auth()->guard('admin')->user()->img ? asset('uploads/admin/avatar/'.auth()->guard('admin')->user()->img) : asset('default.png')}}  "
                     alt="" class="online">
                <span>{{auth()->guard('admin')->user()->name}} <span class="fa fa-angle-down"></span></span>
            </a>
            <div class="sa-left-menu-outer">
                <ul class="metismenu sa-left-menu" id="menu1">

                    @if (adminPermissions(1))
                        <li class=" @if (sidebarActive('admin.admins.index')) active @endif ">
                            <!-- first-level -->
                            <a href="{{route('admin.admins.index')}}" title="Outlook"><span
                                        class="fa fa-lg fa-fw fa-inbox"></span>
                                <span class="menu-item-parent">{{trans('admin.admins')}}</span></a>
                        </li>
                    @endif

                        <li class=" @if (sidebarActive('admin.mobile.index')) active @endif ">
                            <!-- first-level -->
                            <a href="{{route('admin.mobile.index')}}" title="Outlook"><span
                                        class="fa fa-lg fa-fw fa-inbox"></span>
                                <span class="menu-item-parent">{{trans('admin.mobile')}}</span></a>
                        </li>

                    {{-- <li class=" ">
                         <!-- first-level -->
                         <a href="{{route('admin.roles.index')}}" title="Outlook"><span
                                     class="fa fa-lg fa-fw fa-inbox"></span>
                             <span class="menu-item-parent">roles</span></a>
                     </li>--}}

                    @if (adminPermissions(4))
                        <li class=" @if (sidebarActive('admin.settings.index'))active @endif ">
                            <!-- first-level -->
                            <a href="{{route('admin.settings.index')}}" title="Outlook"><span
                                        class="fa fa-lg fa-fw fa-gear"></span> <span
                                        class="menu-item-parent">{{trans('admin.settings')}}</span></a>
                        </li>
                    @endif
                    @if (adminPermissions(5))
                        <li class=" @if (sidebarActive('admin.messages.index'))active @endif ">
                            <!-- first-level -->
                            <a href="{{route('admin.messages.index')}}" title="Outlook"><span
                                        class="fa fa-lg fa-fw fa-envelope-square"></span> <span
                                        class="menu-item-parent">{{trans('admin.messages')}}</span></a>
                        </li>
                    @endif

                </ul>
            </div>
            <a href="javascript:void(0)" class="minifyme" onclick="SAtoggleClass(this, 'body', 'minified')">
                <i class="fa fa-arrow-circle-left hit"></i>
            </a>
        </div>
        <!-- BEGIN .sa-content-wrapper -->
    @yield('content')
    <!-- END .sa-content-wrapper -->


    </div>
    <!-- BEGIN .sa-page-footer -->
    <footer class="sa-page-footer" style="position: fixed;bottom: 0;z-index: 8;">
        <div class="d-flex align-items-center w-100 h-100" style="text-align: center">
            <div class="footer-left w-100">
                SpectraApp &copy;
                2019
            </div>

        </div>
    </footer>
    <!-- END .sa-page-footer -->
</div>

<!-- END .sa-wrapper -->
<script type="text/javascript" src="{{asset('backEnd/sweetalert2.all.min.js')}}"></script>
<script type="text/javascript" src="{{asset('js/admin.js')}}"></script>


<script>
    $(function () {
        $('#menu1').metisMenu();
    });
</script>

<script type="text/javascript">

    /* BASIC ;*/
    var responsiveHelper_dt_basic = responsiveHelper_dt_basic || undefined;
    var responsiveHelper_datatable_fixed_column = responsiveHelper_datatable_fixed_column || undefined;
    var responsiveHelper_datatable_col_reorder = responsiveHelper_datatable_col_reorder || undefined;
    var responsiveHelper_datatable_tabletools = responsiveHelper_datatable_tabletools || undefined;

    var breakpointDefinition = {
        tablet: 1024,
        phone: 480
    };


    /* END COLUMN SHOW - HIDE */

    /* TABLETOOLS */
    $('#datatable_tabletools').dataTable({

        // Tabletools options:
        //   https://datatables.net/extensions/tabletools/button_options
        "sDom": "<'dt-toolbar d-flex'<f><'hidden-xs ml-auto'B>r>" +
            "t" +
            "<'dt-toolbar-footer d-flex'<'hidden-xs'i><'ml-auto'p>>",
        "oLanguage": {
            "sSearch": '<span class="input-group-addon"><i class="fa fa-search"></i></span>'
        },
        "classes": {
            "sW`rapper": "dataTables_wrapper dt-bootstrap4"
        },
        buttons: [{
            extend: 'print',
            className: 'btn btn-default'
        }],
        "autoWidth": true

    });

    /* END TABLETOOLS */


</script>
<script>
    @if(session()->has('success'))
    Swal.fire({
        position: 'center',
        type: 'success',
        title: '{{session()->get('success')}}',
        showConfirmButton: false,
        width: '40rem',
        customClass: "right-check",
        timer: 1500
    });
    @endif
    @if(session()->has('error'))
    Swal.fire({
        type: 'error',
        title: 'حدث خطأ',
        text: '{{session()->get('error')}}',
    });
    @endif
    {{--@if ($errors->any())
    Swal.fire({
        title: '<strong style="font-size: 25px; font-weight: lighter;"> برجاء إصلاح الأخطاء التاليه</strong>',
        type: 'info',
        html: '<p style="font-weight: bold;font-size: 15px;color: red;">' + '{{$errors->first()}}' + '</p>',
        width: '40rem',
    });
    @endif--}}
</script>

<script>
    $(document).ready(function () {
        $('#dt-basic').DataTable({
            "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]]
        });
    });
</script>
<script>
    $('input[type="file"]').each(function () {

        var $file = $(this),
            $label = $file.next('label'),
            $labelText = $label.find('span'),
            labelDefault = $labelText.text();

        $file.on('change', function (event) {
            var fileName = $file.val().split('\\').pop(),
                tmppath = URL.createObjectURL(event.target.files[0]);
            if (fileName) {
                $label
                    .addClass('file-ok')
                    .css('background-image', 'url(' + tmppath + ')');
                $labelText.text(fileName);
            } else {
                $label.removeClass('file-ok');
                $labelText.text(labelDefault);
            }
        });

    });
</script>
@yield('scripts')
</body>

</html>