routes/web.php
<?php

/* Admin Routes */

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.'], function () {

    /*
     *  admin login and logout routes
     */

    Route::group(['prefix' => 'auth', 'as' => 'auth.'], function () {


        Route::get('/login', ['uses' => 'AuthController@index', 'as' => 'get.login']);

        Route::post('/login', ['uses' => 'AuthController@login', 'as' => 'post.login']);

        Route::get('/logout', ['uses' => 'AuthController@logout', 'as' => 'logout']);


    });


    /*Must Login Routes*/

    Route::group(['middleware' => 'admin'], function () {

        /*
         * Change Lang
         */
        Route::group(['as' => 'lang.'], function () {
            Route::get('/lang', ['uses' => 'IndexController@changeLang', 'as' => 'change']);
        });

        /*
        * Dashboard
        */
        Route::group(['as' => 'index.'], function () {
            Route::get('/', ['uses' => 'IndexController@index', 'as' => 'index']);
        });

        /*
                 * Profile
                 */
        Route::group(['prefix' => 'profile', 'as' => 'profile.'], function () {
            Route::get('/', ['uses' => 'ProfileController@index', 'as' => 'index']);
            Route::post('/update', ['uses' => 'ProfileController@update', 'as' => 'update']);
            Route::post('/update-password', ['uses' => 'ProfileController@updatePassword', 'as' => 'update.password']);
        });


        /*
         * Admins
         */
        Route::group(['prefix' => 'admins', 'as' => 'admins.'], function () {

            Route::get('/', ['uses' => 'AdminsController@index', 'as' => 'index']);
            Route::post('/add-admin', ['uses' => 'AdminsController@add', 'as' => 'add']);
            Route::post('/edit-admin', ['uses' => 'AdminsController@edit', 'as' => 'edit']);
            Route::post('/delete-admin', ['uses' => 'AdminsController@delete', 'as' => 'delete']);

        });

        /*
         * Roles
         */
        Route::group(['prefix' => 'roles', 'as' => 'roles.'], function () {

            Route::get('/', ['uses' => 'RolesController@index', 'as' => 'index']);
            Route::post('/add-role', ['uses' => 'RolesController@add', 'as' => 'add']);
            Route::post('/edit-role', ['uses' => 'RolesController@edit', 'as' => 'edit']);
            Route::post('/delete-role', ['uses' => 'RolesController@delete', 'as' => 'delete']);

        });


        /*
        * Settings
        */
        Route::group(['prefix' => 'settings', 'as' => 'settings.'], function () {

            Route::get('/', ['uses' => 'SettingsController@index', 'as' => 'index']);

            // Site details
            Route::post('/edit-details', ['uses' => 'SettingsController@editSiteDetails', 'as' => 'edit.details']);

            // Social
            Route::post('/edit-social', ['uses' => 'SettingsController@editSocial', 'as' => 'edit.social']);

            // About us
            Route::post('/edit-about', ['uses' => 'SettingsController@editAbout', 'as' => 'edit.about']);

            // Team
            Route::post('/add-team', ['uses' => 'SettingsController@addTeam', 'as' => 'add.team']);
            Route::post('/edit-team', ['uses' => 'SettingsController@editTeam', 'as' => 'edit.team']);
            Route::post('/delete-team', ['uses' => 'SettingsController@deleteTeam', 'as' => 'delete.team']);

            // gallery department
            Route::post('/add-gallery-department', ['uses' => 'SettingsController@addGalleryDepartment', 'as' => 'add.gallery.department']);
            Route::post('/edit-gallery-department', ['uses' => 'SettingsController@editGalleryDepartment', 'as' => 'edit.gallery.department']);
            Route::post('/delete-gallery-department', ['uses' => 'SettingsController@deleteGalleryDepartment', 'as' => 'delete.gallery.department']);


            // Gallery
            Route::post('/add-gallery', ['uses' => 'SettingsController@addGallrey', 'as' => 'add.gallery']);
            Route::post('/edit-gallery', ['uses' => 'SettingsController@editGallrey', 'as' => 'edit.gallery']);
            Route::post('/delete-gallery', ['uses' => 'SettingsController@deleteGallrey', 'as' => 'delete.gallery']);

            Route::post('/add-article', ['uses' => 'SettingsController@addArticle', 'as' => 'add.article']);
            Route::post('/edit-article', ['uses' => 'SettingsController@editArticle', 'as' => 'edit.article']);
            Route::post('/delete-article', ['uses' => 'SettingsController@deleteArticle', 'as' => 'delete.article']);

            // Services
            Route::post('/add-service', ['uses' => 'SettingsController@addService', 'as' => 'add.service']);
            Route::post('/edit-service', ['uses' => 'SettingsController@editService', 'as' => 'edit.service']);
            Route::post('/delete-service', ['uses' => 'SettingsController@deleteService', 'as' => 'delete.service']);

            // Web Colors
            Route::post('/edit-web-color', ['uses' => 'SettingsController@editWebColor', 'as' => 'edit.web.color']);

            // Mobile Colors
            Route::post('/edit-mobile-color', ['uses' => 'SettingsController@editMobileColor', 'as' => 'edit.mobile.color']);

            // Web Slider
            Route::post('/add-web-slider', ['uses' => 'SettingsController@addWebSlider', 'as' => 'add.web.slider']);
            Route::post('/edit-web-slider', ['uses' => 'SettingsController@editWebSlider', 'as' => 'edit.web.slider']);
            Route::post('/delete-web-slider', ['uses' => 'SettingsController@deleteWebSlider', 'as' => 'delete.web.slider']);
            Route::post('/web-slider-status', ['uses' => 'SettingsController@webSliderStatus', 'as' => 'web.slider.status']);

            // Mobile Slider
            Route::post('/add-mobile-slider', ['uses' => 'SettingsController@addMobileSlider', 'as' => 'add.mobile.slider']);
            Route::post('/edit-mobile-slider', ['uses' => 'SettingsController@editMobileSlider', 'as' => 'edit.mobile.slider']);
            Route::post('/delete-mobile-slider', ['uses' => 'SettingsController@deleteMobileSlider', 'as' => 'delete.mobile.slider']);
            Route::post('/mobile-slider-status', ['uses' => 'SettingsController@mobileSliderStatus', 'as' => 'mobile.slider.status']);

            Route::post('/add-testmonials', ['uses' => 'SettingsController@addTestmonials', 'as' => 'add.testmonials']);
            Route::post('/edit-testmonials', ['uses' => 'SettingsController@editTestmonials', 'as' => 'edit.testmonials']);
            Route::post('/delete-testmonials', ['uses' => 'SettingsController@deleteTestmonials', 'as' => 'delete.testmonials']);

            Route::post('/add-customer-logo', ['uses' => 'SettingsController@addCustomerLogo', 'as' => 'add.customer.logo']);
            Route::post('/edit-customer-logo', ['uses' => 'SettingsController@editCustomerLogo', 'as' => 'edit.customer.logo']);
            Route::post('/delete-customer-logo', ['uses' => 'SettingsController@deleteCustomerLogo', 'as' => 'delete.customer.logo']);

            Route::post('/add-condition', ['uses' => 'SettingsController@addCondition', 'as' => 'add.condition']);
            Route::post('/edit-condition', ['uses' => 'SettingsController@editCondition', 'as' => 'edit.condition']);
            Route::post('/delete-condition', ['uses' => 'SettingsController@deleteCondition', 'as' => 'delete.condition']);

            Route::post('/add-question', ['uses' => 'SettingsController@addQuestion', 'as' => 'add.question']);
            Route::post('/edit-question', ['uses' => 'SettingsController@editQuestion', 'as' => 'edit.question']);
            Route::post('/delete-question', ['uses' => 'SettingsController@deleteQuestion', 'as' => 'delete.question']);

            Route::post('/add-info', ['uses' => 'SettingsController@addInfo', 'as' => 'add.info']);
            Route::post('/edit-info', ['uses' => 'SettingsController@editInfo', 'as' => 'edit.info']);
            Route::post('/delete-info', ['uses' => 'SettingsController@deleteInfo', 'as' => 'delete.info']);

            Route::post('/add-shi-condition', ['uses' => 'SettingsController@addShCondition', 'as' => 'add.sh.condition']);
            Route::post('/edit-shi-condition', ['uses' => 'SettingsController@editShCondition', 'as' => 'edit.sh.condition']);
            Route::post('/delete-shi-condition', ['uses' => 'SettingsController@deleteShCondition', 'as' => 'delete.sh.condition']);

            // Time

            Route::post('/edit-time', ['uses' => 'SettingsController@editTime', 'as' => 'edit.time']);
            Route::post('/edit-status', ['uses' => 'SettingsController@editStatus', 'as' => 'edit.status']);

            Route::group(['prefix' => 'countries'], function () {

                Route::post('/add-country', ['uses' => 'SettingsController@AddCountry', 'as' => 'add.country']);
                Route::post('/edit-country', ['uses' => 'SettingsController@EditCountry', 'as' => 'edit.country']);
                Route::post('/delete-country', ['uses' => 'SettingsController@DeleteCountry', 'as' => 'delete.country']);

            });

            Route::group(['prefix' => 'provinces'], function () {

                Route::get('/{id}', ['uses' => 'SettingsController@Provinces', 'as' => 'provinces']);
                Route::post('/add-province', ['uses' => 'SettingsController@AddProvince', 'as' => 'add.province']);
                Route::post('/edit-province', ['uses' => 'SettingsController@EditProvince', 'as' => 'edit.province']);
                Route::post('/delete-province', ['uses' => 'SettingsController@DeleteProvince', 'as' => 'delete.province']);

            });

            Route::group(['prefix' => 'cities'], function () {

                Route::get('/{id}', ['uses' => 'SettingsController@Cities', 'as' => 'cities']);
                Route::post('/add-city', ['uses' => 'SettingsController@AddCity', 'as' => 'add.city']);

resources/views/admin/pages/settings/provinces.blade.php
@extends('admin.layouts.Master-Layout')

@section('title')

    {{trans('admin.settings')}}

@stop

@section('content')

    <div class="sa-content-wrapper">

        <div class="sa-content">
            <div class="d-flex w-100 home-header">
                <div>
                    <h1 class="page-header"><i class="fa fa-table fa-fw "></i> {{trans('admin.dashboard')}} <span>> {{trans('admin.settings')}}
								</span></h1>
                </div>
            </div>
            <div>
                <div>

<div class="tab-pane" id="Province" role="tabpanel">
    <!-- widget div-->
    <div style="text-align: center;">
        <a style=" margin-top: 1rem;margin-bottom: 1rem;" href="javascript:void(0);"
           class="btn sa-btn-primary" data-toggle="modal"
           data-target="#myModal-coun"> Add Province</a>

        <a class="btn sa-btn-primary" style=" margin-top: 1rem;margin-bottom: 1rem;" href="{{ URL::previous() }}"> Back</a>

        <!-- Modal  to add supervisor-->
        <div class="modal fade" id="myModal-coun" tabindex="-1" role="dialog"
             aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel"
                            style="font-weight:bold">Add
                            Province</h5>
                        <button type="button" class="close" data-dismiss="modal"
                                aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body" style="text-align:left;">
                        <form action="{{route('admin.settings.add.province')}}"
                              method="post">
                            @csrf
                            <div class="form-group">
                                <label for="exampleInputEmail1">Arabic Province Name</label>
                                <input name="name" type="text" class="form-control"
                                       id="exampleInputText1" placeholder="Province Name">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail1">English Province Name</label>
                                <input name="name_en" type="text" class="form-control"
                                       id="exampleInputText1" placeholder="Province Name">
                            </div>

                            <input type="hidden" name="country_id" value="{{$id}}">

                            <div class="modal-footer" style="margin-top:1rem;">
                                <button type="button" class="btn btn-default"
                                        data-dismiss="modal">Close</button>
                                <button type="submit"
                                        class="btn btn-primary">Save
                                </button>
                            </div>
                        </form>
                    </div>

                </div>
            </div>
        </div>
        <!-- widget content -->
        <div class="widget-body p-0">


            <table id="datatable_tabletools"
                   class="table table-striped table-bordered table-hover"
                   width="100%">
                <thead>
                <tr>
                    <th data-hide="phone">ID</th>
                    <th data-class="expand"> Arabic Province Name</th>
                    <th data-class="expand"> English Province Name</th>

                    <th data-hide="phone">State</th>

                    <th data-hide="phone,tablet">Action</th>

                </tr>
                </thead>
                <tbody>

                @foreach($provinces as $province)

                    <tr>
                        <td>{{$province->id}}</td>
                        <td>{{$province->name}}</td>
                        <td>{{$province->name_en}}</td>
                        <td>
                            <a href="{{route('admin.settings.cities',['id'=>$province->id])}}">show</a>
                        </td>

                        <td>
                            <button class="btn btn-primary" data-toggle="modal"
                                    data-target="#myModal-2{{$province->id}}" style="margin-bottom:10px;"><i
                                        class="fa fa-edit"></i></button>
                            <button class="btn btn-danger" data-toggle="modal"
                                    data-target="#myModal-3{{$province->id}}" style="margin-bottom:10px;"><i
                                        class="fa fa-trash"></i></button>

                        </td>

                    </tr>

                @endforeach

                @foreach($provinces as $province)


                    <!-- Modal  to Edit supervisor-->
                    <div class="modal fade" id="myModal-2{{$province->id}}" tabindex="-1"
                         role="dialog" aria-labelledby="exampleModalLabel"
                         aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title"
                                        id="exampleModalLabel"
                                        style="font-weight:bold">Edit
                                        Country</h5>
                                    <button type="button" class="close"
                                            data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <form action="{{route('admin.settings.edit.province',['id'=>$province->id])}}"
                                      method="post" enctype="multipart/form-data">
                                    @csrf
                                    <div class="modal-body"
                                         style="text-align:left;">
                                        <div class="form-group">
                                            <label
                                                    for="exampleInputEmail1">Arabic Country Name</label>
                                            <input type="text" name="name" value="{{$province->name_ar}}"
                                                   class="form-control"
                                                   id="exampleInputText1"
                                                   placeholder="Country Name">
                                        </div>

                                        <div class="form-group">
                                            <label
                                                    for="exampleInputEmail1">English Country Name</label>
                                            <input type="text" name="name_en" value="{{$province->name_en}}"
                                                   class="form-control"
                                                   id="exampleInputText1"
                                                   placeholder="Country Name">
                                        </div>

                                        <div class="modal-footer"
                                             style="margin-top:1rem;">
                                            <button type="button"
                                                    class="btn btn-default"
                                                    data-dismiss="modal">Close</button>
                                            <button type="submit"
                                                    class="btn btn-primary">Save
                                                changes</button>
                                        </div>
                                    </div>
                                </form>
                            </div>

                        </div>
                    </div>

                    <!-- Modal to delet supervisor -->
                    <div class="modal fade" id="myModal-3{{$province->id}}" tabindex="-1"
                         role="dialog" aria-labelledby="exampleModalLabel"
                         aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title"
                                        id="exampleModalLabel"
                                        style="font-weight:bold">Delet
                                        Country</h5>
                                    <button type="button" class="close"
                                            data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <form action="{{route('admin.settings.delete.province',['id'=>$province->id])}}"
                                      method="post">
                                    @csrf
                                    <div class="modal-body"
                                         style="text-align:left;">
                                        Are you sure you want to <strong>Delet This
                                            Country </strong> ?
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button"
                                                class="btn btn-default"
                                                data-dismiss="modal">No</button>
                                        <button type="submit"
                                                class="btn btn-primary">Yes</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                @endforeach

                </tbody>
            </table>

        </div>
        <!-- end widget content -->

    </div>
    <!-- end widget div -->
</div>

    @stop

                </div>
            </div>
        </div>

    </div>

@section('scripts')
    <script>
        $('#tabs').tabs();
        // Dynamic tabs
        var tabTitle = $("#tab_title"), tabContent = $("#tab_content"),
            tabTemplate = "<li style='position:relative;'> <span class='air air-top-left delete-tab' style='top:5px; left:5px;'><button class='btn btn-xs font-xs btn-default hover-transparent'><i class='fa fa-times'></i></button></span></span><a href='#{href}'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; #{label}</a></li>",
            tabCounter = 2;

        var tabs = $("#tabs2").tabs();

        // modal dialog init: custom buttons and a "close" callback reseting the form inside
        var dialog = $("#addtab").dialog({
            autoOpen: false,
            width: 600,
            resizable: false,
            modal: true,
            buttons: [{
                html: "<i class='fa fa-times'></i>&nbsp; Cancel",
                "class": "btn btn-default",
                click: function () {
                    $(this).dialog("close");

                }
            }, {

                html: "<i class='fa fa-plus'></i>&nbsp; Add",
                "class": "btn sa-btn-danger",
                click: function () {
                    addTab();
                    $(this).dialog("close");
                }
            }]
        });
        // addTab form: calls addTab function on submit and closes the dialog
        var form = dialog.find("form").submit(function (event) {
            addTab();
            dialog.dialog("close");
            event.preventDefault();
        });

        // actual addTab function: adds new tab using the input from the form above

    </script>

    <script>
        $(document).on("change", ".status", function () {
            var status = $(this).val();
            var id = $(this).attr("uid");
            var token = "{{ csrf_token() }}";
            $.ajax({
                url: "{{ route('admin.settings.edit.status') }}",
                type: "post",
                dataType: "json",
                data: {status: status, id: id, _token: token},
                success: function (data) {
                    Swal.fire({
                        position: 'center',
                        type: 'success',
                        title: data.message,
                        showConfirmButton: false,
                        width: '40rem',
                        customClass: "right-check",
                        timer: 1500
                    });
                    if (data.status !== "1") {
                        Swal.fire({
                            type: 'error',
                            title: 'حدث خطأ',
                        });
                    }
                },
                error: function () {
                    Swal.fire({
                        type: 'error',
                        title: 'حدث خطأ',
                    });
                }
            })
        })
    </script>

@stop